### ISSUE TITLE
Mi4C

### ISSUE THREAD

**Issue by tomaatti** [dogiex/MA-XML-7.0-FINNISH#1]
Mites tämä käännös taipuu Libralle kun näköjään Cancro on tuolla pohjissa mainittu, pitäiskö avata jotain myös Libralle?

**Comment by dogiex** [comment]
Main kansiossa olevat käännökset tulee toimimaan kaikissa xiaomin laitteissa, koska MIUI on kuitenkin kaikissa lähes sama. Toki laitekohtaisia eroja on jonkin verran ja ne pyritään tekemään kanssa kunhan ensiksi perus käyttis saadaan käännettyä niin katsellaan sen jälkeen noi laitekohtaiset käännökset. ;)

**Comment by tomaatti** [comment]
Jep.
